def main():
    Q1 = float(input("How many numbers do you want to take the average of? (1-10) "))
    if Q1 == 1:
        Q2 = float(input("Please enter your 1st number: "))
        Average = (Q1 /Q2)
        print(f"your average is {Average}")
    if Q1 == 2:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Average = (Q1 /Q2)
        print(f"your average is {Average}")
    if Q1 == 3:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Average = ((Q2 + Q3 + Q4) / Q1)
        print(f"your average is {Average}")
    if Q1 == 4:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5) / Q1)
        print(f"your average is {Average}")
    if Q1 == 5:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6) / Q1)
        print(f"your average is {Average}")
    if Q1 == 6:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Q7 = float(input("Please enter your 6th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6 + Q7) / Q1)
        print(f"your average is {Average}")
    if Q1 == 7:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Q7 = float(input("Please enter your 6th number: "))
        Q8 = float(input("Please enter your 7th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6 + Q7 + Q8) / Q1)
        print(f"your average is {Average}")
    if Q1 == 8:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Q7 = float(input("Please enter your 6th number: "))
        Q8 = float(input("Please enter your 7th number: "))
        Q9 = float(input("Please enter your 8th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6 + Q7 + Q8 + Q9) / Q1)
        print(f"your average is {Average}")
    if Q1 == 9:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Q7 = float(input("Please enter your 6th number: "))
        Q8 = float(input("Please enter your 7th number: "))
        Q9 = float(input("Please enter your 8th number: "))
        Q10 = float(input("Please enter your 9th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6 + Q7 + Q8 + Q9 + Q10) / Q1)
        print(f"your average is {Average}")
    if Q1 == 10:
        Q2 = float(input("Please enter your 1st number: "))
        Q3 = float(input("Please enter your 2nd number: "))
        Q4 = float(input("Please enter your 3rd number: "))
        Q5 = float(input("Please enter your 4th number: "))
        Q6 = float(input("Please enter your 5th number: "))
        Q7 = float(input("Please enter your 6th number: "))
        Q8 = float(input("Please enter your 7th number: "))
        Q9 = float(input("Please enter your 8th number: "))
        Q10 = float(input("Please enter your 9th number: "))
        Q11 = float(input("Please enter your 10th number: "))
        Average = ((Q2 + Q3 + Q4 + Q5 + Q6 + Q7 + Q8 + Q9 + Q10 + Q11) / Q1)
        print(f"your average is {Average}")
main()